package com.connectit.core;

import com.connectit.core.util.SimpleHash;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ActiveProfiles("test")
class CoreServiceApplicationTests {

    @org.springframework.beans.factory.annotation.Autowired
    private org.springframework.jdbc.core.JdbcTemplate jdbcTemplate;

    @Test
    void databaseSeeder_seedsDefaultDataSuccessfully() {
        // Verify default settings categories are seeded
        Integer categoryCount = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM settings_categories WHERE id IN ('cat_default_1', 'cat_default_2')", Integer.class
        );
        assertEquals(2, categoryCount, "Settings categories should be seeded");

        // Verify default settings subcategories are seeded and linked
        java.util.List<java.util.Map<String, Object>> subcategories = jdbcTemplate.queryForList(
            "SELECT category_id FROM settings_subcategories WHERE id IN ('sub_default_1', 'sub_default_2', 'sub_default_3')"
        );
        assertEquals(3, subcategories.size(), "Three subcategories should be seeded");
        for (java.util.Map<String, Object> sub : subcategories) {
            assertNotNull(sub.get("category_id"), "Subcategory parent category_id must not be null");
        }

        // Verify default incident categories are seeded
        Integer incidentCategoryCount = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM incident_categories", Integer.class
        );
        assertTrue(incidentCategoryCount >= 10, "At least 10 incident categories should be seeded");
    }

    @Test
    void subcategoryCreation_linksParentCategoryIdCorrectly() {
        String testSubId = "sub_test_" + System.currentTimeMillis();
        String testCatId = "cat_default_1"; // IT Support

        // Insert subcategory simulating Settings page creation payload
        jdbcTemplate.update(
            "INSERT INTO settings_subcategories (id, name, description, category_id, status, company_id) VALUES (?, ?, ?, ?, ?, ?)",
            testSubId, "z", "z description", testCatId, "active", "1"
        );

        // Fetch back and assert linkage
        java.util.Map<String, Object> subcategory = jdbcTemplate.queryForMap(
            "SELECT category_id FROM settings_subcategories WHERE id = ?", testSubId
        );
        assertEquals(testCatId, subcategory.get("category_id"), "Created subcategory must have the correct category_id linked");

        // Clean up
        jdbcTemplate.update("DELETE FROM settings_subcategories WHERE id = ?", testSubId);
    }

    @Test
    void simpleHash_matchesJavaScriptBehavior() {
        // These values were generated by the original JS simpleHash("Poland@01")
        String hash = SimpleHash.hash("Poland@01");
        assertNotNull(hash);
        assertTrue(hash.startsWith("h_"));
        // Format: h_<base36>_<length>
        String[] parts = hash.split("_");
        assertEquals(3, parts.length);
        assertEquals("9", parts[2]); // "Poland@01" is 9 chars
    }

    @Test
    void simpleHash_differentPasswordsDifferentHashes() {
        assertNotEquals(SimpleHash.hash("password1"), SimpleHash.hash("password2"));
    }

    @Test
    void simpleHash_consistentResults() {
        assertEquals(SimpleHash.hash("test123"), SimpleHash.hash("test123"));
    }
}
